import type { Metadata } from "next";
import "../public/globals.css";
import { satoshi } from "@/lib/utils/fonts";
import Providers from "@/lib/utils/providers";

export const metadata: Metadata = {
  title: "Smartlink Generator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={satoshi.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
